application: annafacts
version: reporting
runtime: python
api_version: 1

derived_file_type:
- python_precompiled

inbound_services:
- xmpp_message
- mail

handlers:
- url: .*
  script: main.py
